### ISSUE TITLE
problem with recording states

### ISSUE THREAD

**Issue by zms2003** [rp3tya/PCF8575#1]
There is a problem with recording in pcf8575
Only the last 8 ports are changed.
I looked at the source code of the package. I think you need to change the port recording command. It should be something like this:
It was:
self.bus.write_byte_data(self.address, new_state & 0xff, (new_state & 0xff ) >> 8) - only last 8 bits working

should be:
self.bus.write_byte_data(self.address, 0x00, new_state)
Direct recording works for me like this:
i2c.write_byte_data(pcf7585_adress, 0x00, 0b1111111111111111) - it's working

**Comment by rp3tya** [comment]
Thanks for pointing that out! Can you please make a pull request?

**Comment by zms2003** [comment]
i'm sorry, my post is wrong... but your package is not working with 2th byte... Now I use direct read-write without package

**Comment by rp3tya** [comment]
Can you please share your code. I do not have a board to test with, but would like to fix the package if it is not working...

**Comment by zms2003** [comment]
writing - i2c.write_byte_data(pcf7585_adress, first_byte, second_byte)
reading - temp = i2c.read_word_data(pcf7585_adress, 0)
befor working with inputs you must send 1 to input port

**Comment by rp3tya** [comment]
Can you please test v0.3 (still output only). The second byte was indeed composed incorrectly...

**Comment by zms2003** [comment]
Ok. Tomorrow.

**Comment by zms2003** [comment]
I'm checking package. pcf.port working now))  all package i'm don't tested
