### ISSUE TITLE
board's num is not the same list index. 

### ISSUE THREAD

**Issue by Fosity** [rp3tya/PCF8575#2]
```   
 def set_output(self, output_number, value):
        """
        Set a specific output high (True) or low (False).
        """
        assert output_number in range(16), "Output number must be an integer between 0 and 15"
        current_state = self.bus.read_word_data(self.address, 0)
        bit = 1 << 15-output_number
        new_state = current_state | bit if value else current_state & (~bit & 0xff)
        self.bus.write_byte_data(self.address, new_state & 0xff, (new_state >> 8) & 0xff)
```

i think
```  
     new_state = current_state | bit if value else current_state & (~bit )
```
and
```
all  `15-i`   replace `i`   
```
maybe is right.
board's num is not the same list index.

**Comment by pepcio03** [comment]
i think

`new_state = current_state | bit if value else current_state & (~bit & 0xff)`

to
 `new_state = current_state | bit if value else current_state & (~bit & 0xffff)`

and now work

**Comment by mdbingers** [comment]
@pepcio03 - I think you're right!  I found the same issue while trying to get my boards to work.  The current code seems to only handles the first two bytes and incorrectly sets the second two bytes to zero on every set_output call.
